I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 109, in script
    antonio "\"RISE N SHINE MY BOY!\""
  File "game/script.rpy", line 22, in antonio_voice
    if begin == "show_done":
NameError: global name 'begin' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 109, in script
    antonio "\"RISE N SHINE MY BOY!\""
  File "C:\Users\jadal\Desktop\renpy-7.4.10-sdk/renpy/ast.py", line 721, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\jadal\Desktop\renpy-7.4.10-sdk/renpy/exports.py", line 1417, in say
    who(what, *args, **kwargs)
  File "C:\Users\jadal\Desktop\renpy-7.4.10-sdk/renpy/character.py", line 1249, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "C:\Users\jadal\Desktop\renpy-7.4.10-sdk/renpy/character.py", line 901, in do_display
    **display_args)
  File "C:\Users\jadal\Desktop\renpy-7.4.10-sdk/renpy/character.py", line 485, in display_say
    c("begin", interact=interact, type=type, **cb_args)
  File "game/script.rpy", line 22, in antonio_voice
    if begin == "show_done":
NameError: global name 'begin' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.10.2178
Insect Incest 1.0
Sun Nov 21 16:50:03 2021
